### Create a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My first blog",
  "author": "Andrew",
  "url": "http://myblog8.com",
  "likes": 3
}

### envío de un blog con userId
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My first blog",
  "author": "Andrew",
  "url": "http://myblog10.com",
  "likes": 3,
  "userId": "6a19b3d7171e3699e0cc58c4"
}