### Create a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My first blog",
  "author": "Andrew",
  "url": "http://myblog8.com",
  "likes": 3
}

### envío de un blog con userId
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My first blog",
  "author": "Andrew",
  "url": "http://myblog14.com",
  "likes": 3,
  "userId": "6a19b3d7171e3699e0cc58c4"
}

### crecion de blog con token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFuZHJldyIsImlkIjoiNmExOWIzZDcxNzFlMzY5OWUwY2M1OGM0IiwiaWF0IjoxNzgwMjQ0NjM2fQ.vAZraESyP2totYp-OO_zbpezs3xDfJgiH62PlX25yzg

{
  "title": "My fourth blog",
  "author": "Andrew",
  "url": "http://myblog14.com",
  "likes": 3
}