### Agregar usuario
POST http://localhost:3001/api/persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhMTc1MTNiNzg5YTRiY2FiMTg1MTg4NyIsImlhdCI6MTc4MDI0NjgxMSwiZXhwIjoxNzgwMjUwNDExfQ.QdgE2eXG9UTBtl2pnZGpJUmhJOENGJ5sARF91GX1_Cw

{
  "name": "andres david murillo B",
  "number": "1234567890"

}

### creacion de notas sin token jwt
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "root",
  "number": "salainen"

}

